[package]
name = "mannequin"
version = "0.2.0"
authors = ["Stefan Ulbrich"]
documentation = "https://github.com/biomechanics-foundation/mannequin"
edition = "2021"
homepage = "https://github.com/biomechanics-foundation/mannequin"
license = "MIT OR Apache-2.0"
repository = "https://github.com/biomechanics-foundation/mannequin"
rust-version = "1.67"

readme = "Readme.md"
description = "Direkt and inverse kinematics for biomechanics, robotics and character animation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.13.0"
ndarray = { version = "0.16.1", optional = true, features = ["approx", "rayon"] }
smallvec = { version = "1.13.2", optional = true }
thiserror = "2.0.7"
tracing = "0.1.41"
tracing-attributes = "0.1.28"

[features]
ndarray = ["dep:ndarray", "dep:smallvec"]

[dev-dependencies]
test-log = { version = "0.2.16", features = ["trace"] }
