[package]
name = "mannequin"
version = "0.2.0"
authors = ["Stefan Ulbrich"]
documentation = "https://github.com/biomechanics-foundation/mannequin"
edition = "2021"
homepage = "https://github.com/biomechanics-foundation/mannequin"
license = "MIT OR Apache-2.0"
repository = "https://github.com/biomechanics-foundation/mannequin"

readme = "Readme.md"
description = "Direkt and inverse kinematics for biomechanics, robotics and character animation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.13.0"
ndarray = { version = "0.16.1", optional = true, features = ["approx", "blas", "rayon"] }
thiserror = "2.0.4"

[features]
ndarray = ["dep:ndarray"]
